apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server-container
          image: abhilashbalaji/sc-server:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 5000
              name: server

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: server
