apiVersion: v1
kind: Service
metadata:
   name: ui-entrypoint
spec:
   type: NodePort
   selector:
      app: react-nginx-app
   ports:
      - port: 8091
        targetPort: 80
        nodePort: 30003
        protocol: TCP
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: react-nginx-app
   labels:
      app: react-nginx-app
spec:
   replicas: 1
   selector:
      matchLabels:
         app: react-nginx-app
   template:
      metadata:
         labels:
            app: react-nginx-app
      spec:
         containers:
         - name: react-nginx-app
           image: abhilashbalaji/ui:latest
           imagePullPolicy: Always
           ports:
           - containerPort: 80