apiVersion: apps/v1
kind: Deployment
metadata:
   name: react-nginx-app
   labels:
      app: react-nginx-app
spec:
   replicas: 1
   selector:
      matchLabels:
         app: react-nginx-app
   template:
      metadata:
         labels:
            app: react-nginx-app
      spec:
         containers:
         - name: react-nginx-app
           image: svenlankester/ui:latest
           imagePullPolicy: Always
           ports:
           - containerPort: 80
---
