apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: server
        {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: server-container
          image: abhilashbalaji/sc-server:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOST
              value: db-service
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 5000
              name: server

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31640
  selector:
    app: server
