


apiVersion: v1
kind: Service
metadata:
   name: ui-entrypoint
spec:
   type: NodePort
   selector:
      app: react-nginx-app
   ports:
      - port: 8091
        targetPort: 80
        nodePort: 30003
        protocol: TCP
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: react-nginx-app
   labels:
      app: react-nginx-app
      {{- include "mychart.labels" . | nindent 4 }}
spec:
   replicas: 2
   selector:
      matchLabels:
         app: react-nginx-app
         {{- include "mychart.selectorLabels" . | nindent 6 }}
   template:
      metadata:
         labels:
            app: react-nginx-app
            {{- include "mychart.selectorLabels" . | nindent 8 }}
      spec:
         containers:
         - name: react-nginx-app
           image: nielsbk/ui:test
           imagePullPolicy: Always
           ports:
           - containerPort: 80